### PR TITLE
Modified App.js

### PR DESCRIPTION
**Pull request by Abirami97**
Removed the pop-up messages when weather changes.

### CODE REVIEW

**Review by yurina — CHANGES_REQUESTED** [review]
is it supposed to be editing of the existing file at `src/App.js`? seems like in this PR you add new App.js file to a root folder

**Comment by Abirami97** [comment]
> is it supposed to be editing of the existing file at `src/App.js`? seems like in this PR you add new App.js file to a root folder

I modified the existing App.js and uploaded that file again, Should I do it in a different way?

**Comment by yurina** [comment]
> > is it supposed to be editing of the existing file at `src/App.js`? seems like in this PR you add new App.js file to a root folder
> 
> I modified the existing App.js and uploaded that file again, Should I do it in a different way?
I'm not sure what do you mean by "upload this file again", but if you check codebase at your feature branch you can see that you have 2 App.js files there: one App.js file is at the main folder and second App.js is in `src` folder
https://github.com/Abirami97/WeatherApplication/tree/feature/Remove-popup

So it needs to be only "modify the existing App.js" that is under `src` folder

**Comment by Abirami97** [comment]
> > > is it supposed to be editing of the existing file at `src/App.js`? seems like in this PR you add new App.js file to a root folder
> > 
> > 
> > I modified the existing App.js and uploaded that file again, Should I do it in a different way?
> > I'm not sure what do you mean by "upload this file again", but if you check codebase at your feature branch you can see that you have 2 App.js files there: one App.js file is at the main folder and second App.js is in `src` folder
> > https://github.com/Abirami97/WeatherApplication/tree/feature/Remove-popup
> 
> So it needs to be only "modify the existing App.js" that is under `src` folder

Okay I got what you are saying, will look into it

**Comment by Abirami97** [comment]
Closing the PR as this change will be done by PR #4.

**Comment by yurina** [comment]
Reopen this to practice

**Review by yurina — APPROVED** [review]
👍

**Pull request merged**
